name: Create Snapshot Release

on:
  workflow_run:
    workflows: ["Run Backend Tests"]   # run snapshot release if tests workflow ran ( so runs on every commit )
    types:
      - completed

jobs:
  release: # continue with snap shot only if tests passed
    if: ${{ github.event.workflow_run.conclusion == 'success' }}   
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create zip archive
        run: |
          zip -r snapshot_${{ github.sha }}.zip .

      - name: Calculate snapshot number
        id: calc
        run: echo "SNAP_NUM=$(( $GITHUB_RUN_NUMBER + 3 ))" >> $GITHUB_ENV

      - name: Create GitHub release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: snapshot-${{ env.SNAP_NUM }}
          name: "Snapshot #${{ env.SNAP_NUM }}"
          body: |
            **Snapshot created automatically**
            - Commit: ${{ github.sha }}
            - Author: ${{ github.actor }}
            - Date: ${{ github.event.head_commit.timestamp }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload snapshot asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: snapshot-${{ env.SNAP_NUM }}
          files: snapshot_${{ github.sha }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
